{% set name = "Flask-Admin" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24cae2af832b6a611a01d7dc35f42d266c1d6c75a426b869d8cb241b78233369

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - flask >=0.7
    - wtforms

test:
  imports:
    - flask_admin
    - flask_admin.contrib
    - flask_admin.contrib.fileadmin
    - flask_admin.form
    - flask_admin.model
    - flask_admin.translations
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/flask-admin/flask-admin/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Simple and extensible admin interface framework for Flask
  doc_url: https://flask-admin.readthedocs.io/
  dev_url: https://github.com/flask-admin/flask-admin/
  description: |
    Flask-Admin is a batteries-included, simple-to-use Flask
    extension that lets you add admin interfaces to Flask
    applications. It is inspired by the django-admin package,
    but implemented in such a way that the developer has
    total control of the look, feel and functionality of the
    resulting application.

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
