travis:
  secure:
    BINSTAR_TOKEN: rwKz37jT0+0ZAkYmRstl1BfsICxLmLZr5LqZjNKh1sUGk+pJF9klIHIk4COaktrGDhquE7Osozw/L4hs8q9G50gb6y3D8KGn/JnTZPFYcJa1cTy3FWnGEC5PAkhHR2Yl06aKmwDL62gJww6OMfSAlZzasg6G5izF5XprVQ1IXPsgOO3q1k913SOFa1e6zo4o1udewHQDaUDOX64PMktA6pyG6w7AyUpW+1nvhF/gDxxR5t0tL8qqpjQi+dJljZGKm79crrgx3sGIVHRG+iwx8+E5dLNfG65FjtXGBpG/bqfrGIH2o8YaK7T6bm6coXxTe1qE64Qj5jumHteOwvkt+NvVZsAXZWSUNly7N1SG00wYzvUeKeHvuCKiny1DtrcDYzGO72a18gdGNhl9NDA5m+8pamVK8kJeeB4aY67KDM71dwDOHZItCv0Qbv8xv89SyMxQgInLC921TKiWbnh4X6C+CdoyPZJo+bBGUdwT267MwntGhcjlTzd3GFxUEOqiOLCOMQTu/ndPI3QpNXSkx89k5Q6WqdsBoPBpgVBumWLSSxXw97G9csfpj2enUDywhWpuTzbg92HlQY79GGFIw1Uqa9w6akRBaREtoNjt9Fhy8Y5dqGfFfwxMFgNGIcN4dGXrKR1PU9dJD82FkhZDtib61yVe8JOZyuVyRcI5AW0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
